### ISSUE TITLE
🐞 Error occured in remaining_courses function because of wrong hardcoded tuple

### ISSUE THREAD

**Issue by JeukHwang** [jadehaus/UCE-KAIST-Public#1]
https://github.com/jadehaus/UCE-KAIST-Public/blob/423ef618e0ccdd6c3efcba93a43f9cba72cedd44/app/models.py#L1296
```python
major_mandatory.append((["AE490", "AE401"], 1)) # Suggested code by me
# AE401 is 항공우주시스템설계Ⅱ, AE490 is graduation research
# AE401 can replace AE490 => only one of them is required => the last value of tuple must be 1
```
Offical reference about graudation requirements: https://bulletin.kaist.ac.kr/html/kr/?year=2022&id=kr20221203&file=E

Sorry, I reproduce this error on website and **the production server is down** because of this error 😢 
The error is caused in the following line
https://github.com/jadehaus/UCE-KAIST-Public/blob/423ef618e0ccdd6c3efcba93a43f9cba72cedd44/app/models.py#L1362

**Comment by babam6a** [comment]
Thank you for your participation! We fixed it.
